### PR TITLE
✨ Add an app header

### PR DESCRIPTION
**Pull request by sweisz**
- add an App header
- upload Note Icon
- add an Green accent color to `global.css`

### CODE REVIEW

**Review by DNaunin — APPROVED** [review]
GJ! 🎸

**Review by mrana17 — APPROVED** [review]

**Review by mrana17 — COMMENTED** [review]
GJ 🚀

**Review by phlgr — APPROVED** [review]
GJ 🚀

**Review by phlgr — CHANGES_REQUESTED** [review]
.

**Pull request merged**
